---
version: 0.2

# env:
#   variables:
#     DOCS_ROOT: /tmp/website
#   parameter-store:
#     DEPLOY_BUCKET_NAME: _DEPLOY_BUCKET

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - echo ${CODEBUILD_SOURCE_VERSION}
      - echo pip installed below
      - echo `pip freeze`
  build:
    commands:
      - make html
  post_build:
    commands:
      - echo "Deploy to S3 ${DEPLOY_BUCKET}"
      - aws s3 sync --exact-timestamp --delete build/html s3://${DEPLOY_BUCKET}/
